-- 018: Client feedback (2026-09-27) on the compact-alert work:
--   • The alert text dropped the team/game name when it got compacted —
--     restore it (the code alone means nothing without a legend).
--   • Drop 2H/1Q/2Q/3Q/4Q entirely — just Full Game and 1H. (This also cuts
--     the period-poll cost by ~6x, since only 4 markets are requested per
--     game instead of 24 — the client is fine moving that refresh to 15 min.)
--   • Move forward with real text messages (the app can't ship to the store
--     yet — needs an LLC first). Every user already has a phone number on
--     file from signup (profiles.phone) — nothing new to collect.
--   • Results still aren't texted/app-notified — stays as its own area
--     (already true from migration 017, unchanged here).
--   • The player should see ONLY the play we send them — no comparison to
--     other books. Admin keeps the full comparison.
--
-- SMS delivery note: pg_net's http_post hard-requires Content-Type:
-- application/json (verified live — it rejects any other value), but
-- Twilio's Messages API requires application/x-www-form-urlencoded (verified
-- against Twilio's own docs). Postgres literally cannot call Twilio directly.
-- This migration queues exactly who gets texted and the exact message body
-- into sms_outbox; the last step (a small relay that reads sms_outbox and
-- calls Twilio) needs Twilio credentials this session doesn't have and a
-- decision on where that relay runs — see the report for options.

-- ============================================================
-- SHARED ALERT TEXT — one wording, used by push AND (queued) SMS
-- ============================================================
create or replace function public.engine_edge_alert_text(e public.edges, p_balance numeric, p_kelly numeric)
returns text
language sql
stable
as $$
  with d as (
    select case when e.local_odds > 0 then 1 + e.local_odds / 100.0
                else 1 + 100.0 / abs(e.local_odds) end as v_dec
  )
  select (case when e.rotation_number is not null then '#' || e.rotation_number || ' ' else '' end)
    || e.matchup || E'\n' || e.specific_bet
    || ' (' || (case when e.local_odds > 0 then '+' else '' end) || e.local_odds || ')'
    || ' · ' || to_char(e.edge_pct, 'FM990.0') || '% edge'
    || ' · Play $' || greatest(0, round(
         coalesce(p_balance, 0) * (e.edge_pct / 100.0) * d.v_dec / (d.v_dec - 1) * (p_kelly / 100.0)))::text
    || ' · ' || e.local_book
    || ' · ' || to_char(e.game_time at time zone 'America/New_York', 'Dy, Mon FMDD FMHH12:MI AM') || ' ET'
  from d;
$$;

-- ============================================================
-- PUSH — same body as before, generated by the shared helper now
-- (restores the matchup/team name the previous compact rewrite dropped)
-- ============================================================
create or replace function public.push_notify_edge()
returns trigger
language plpgsql security definer
set search_path = public
as $$
declare
  v_messages jsonb;
  v_is_high boolean := new.edge_pct >= 4;
begin
  if not public.edge_alerts_enabled() then return new; end if;
  select jsonb_agg(jsonb_build_object(
    'to', pt.token,
    'title', '⚡ ' || to_char(new.edge_pct, 'FM990.0') || '% Edge — ' || new.sport,
    'body', public.engine_edge_alert_text(new, coalesce(b.balance, 0), s.kelly_fraction),
    'data', jsonb_build_object('type', 'edge', 'edgeId', new.id),
    'sound', 'default',
    'priority', 'high',
    'channelId', case when v_is_high and s.high_edge_alerts then 'high-edge' else 'edges' end
  ))
  into v_messages
  from public.push_tokens pt
  join public.profiles p on p.id = pt.user_id and p.is_active
  join public.user_settings s on s.user_id = pt.user_id
  left join public.bankrolls b on b.user_id = pt.user_id
  where s.push_alerts
    and not public.in_quiet_hours(s);

  if v_messages is not null then
    perform public.send_expo_push(v_messages);
  end if;
  return new;
end;
$$;

-- ============================================================
-- SMS OUTBOX — queues who/what; a separate relay (not built here — see
-- the report) does the actual Twilio call
-- ============================================================
create table if not exists public.sms_outbox (
  id bigint generated always as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  phone text not null,
  body text not null,
  edge_id uuid references public.edges(id) on delete set null,
  status text not null default 'pending' check (status in ('pending', 'sent', 'failed')),
  created_at timestamptz not null default now(),
  sent_at timestamptz,
  error text
);
create index if not exists sms_outbox_pending_idx on public.sms_outbox (created_at) where status = 'pending';

alter table public.sms_outbox enable row level security;
drop policy if exists "sms_outbox_admin" on public.sms_outbox;
create policy "sms_outbox_admin" on public.sms_outbox for select using (public.is_admin());

create or replace function public.queue_sms_edge()
returns trigger
language plpgsql security definer
set search_path = public
as $$
begin
  if not public.edge_alerts_enabled() then return new; end if;
  insert into public.sms_outbox (user_id, phone, body, edge_id)
  select s.user_id, p.phone,
         public.engine_edge_alert_text(new, coalesce(b.balance, 0), s.kelly_fraction),
         new.id
  from public.user_settings s
  join public.profiles p on p.id = s.user_id and p.is_active
  left join public.bankrolls b on b.user_id = s.user_id
  where s.sms_alerts
    and p.phone is not null and length(trim(p.phone)) > 0
    and not public.in_quiet_hours(s);
  return new;
end;
$$;
drop trigger if exists queue_sms_edge on public.edges;
create trigger queue_sms_edge
  after insert on public.edges
  for each row execute function public.queue_sms_edge();

revoke execute on function public.engine_edge_alert_text(public.edges, numeric, numeric) from public, anon, authenticated;
revoke execute on function public.queue_sms_edge() from public, anon, authenticated;

-- ============================================================
-- PERIODS — Full Game and 1H only (drop 2H/1Q/2Q/3Q/4Q)
-- ============================================================
create or replace function public.engine_maybe_poll_periods()
returns void
language plpgsql security definer
set search_path = public
as $$
declare
  v_interval int := public.engine_cfg_int('period_refresh_minutes', 120);
  v_window int := public.engine_cfg_int('period_window_hours', 30);
  v_cap int := public.engine_cfg_int('period_daily_credit_cap', 800);
  v_reserve int := public.engine_cfg_int('credit_reserve', 500);
  v_batch int := 4;
  v_state public.engine_state%rowtype;
  v_key text; v_books text; v_markets text; v_url text; v_req bigint;
  v_day date := (now() at time zone 'America/New_York')::date;
  v_spent int; v_inflight int; v_recent int; v_hourly int; v_budget int; v_g record; v_fired int := 0;
begin
  if not coalesce((public.engine_cfg('engine_enabled') #>> '{}')::boolean, false) then return; end if;
  if not coalesce((public.engine_cfg('period_lines_enabled') #>> '{}')::boolean, false) then return; end if;

  select * into v_state from public.engine_state where id = 1;
  if v_state.credits_remaining is null or v_state.credits_remaining <= v_reserve then return; end if;

  v_cap := least(v_cap, floor((v_state.credits_remaining - v_reserve) * 0.10)::int);
  select coalesce(sum(credits), 0) into v_spent from public.engine_period_spend where day = v_day;
  select count(*) into v_inflight from public.engine_requests where req_type = 'period' and not processed;
  -- games fetched in the last hour (in-flight ones are already stamped), at their learned cost
  select coalesce(sum(coalesce(period_cost, 4)), 0) into v_recent
    from public.games where period_polled_at > now() - interval '60 minutes';
  v_hourly := greatest(ceil(v_cap / 4.0)::int, 50);
  v_budget := least(v_cap - v_spent - v_inflight * 4, v_hourly - v_recent);
  if v_budget < 2 then return; end if;

  select value into v_key from private.secrets where name = 'odds_api_key';
  if v_key is null then return; end if;

  select string_agg(distinct k, ',') into v_books
  from (
    select m.api_key as k from public.api_book_map m
    where m.display_name = any(public.engine_cfg_list('active_books'))
    union select 'pinnacle'
  ) t;

  -- 1H only (client: "just game and 1H") — h2h3 kept for the 3-way tie price
  select string_agg(public.engine_api_market(b, p), ',') into v_markets
  from unnest(array['h2h','h2h3','spreads','totals']) b,
       unnest(array['1H']) p;

  for v_g in
    select g.id, g.api_sport, g.sport, coalesce(g.period_cost, 4) as est
    from public.games g
    where g.sport = any(public.engine_cfg_list('board_sports'))
      and g.commence_time > now() + interval '10 minutes'
      and g.commence_time <= now() + make_interval(hours => v_window)
      and (g.period_polled_at is null
           or g.period_polled_at <= now() - make_interval(
                mins => case when g.period_cost = 0 then greatest(v_interval * 3, 360) else v_interval end))
      and not exists (select 1 from public.engine_requests r
                      where r.req_type = 'period' and r.event_id = g.id and not r.processed)
    order by g.commence_time, g.id
    limit v_batch
  loop
    exit when v_budget < v_g.est;
    v_url := 'https://api.the-odds-api.com/v4/sports/' || v_g.api_sport || '/events/' || v_g.id
          || '/odds?apiKey=' || v_key
          || '&bookmakers=' || v_books
          || '&markets=' || v_markets
          || '&oddsFormat=american';
    v_req := net.http_get(url := v_url, timeout_milliseconds := 20000);
    insert into public.engine_requests (request_id, sport, api_sport, req_type, event_id)
    values (v_req, v_g.sport, v_g.api_sport, 'period', v_g.id);
    update public.games set period_polled_at = now() where id = v_g.id;
    v_budget := v_budget - v_g.est;
    v_fired := v_fired + 1;
  end loop;
end;
$$;

create or replace function public.engine_process_pending()
returns void
language plpgsql security definer
set search_path = public
as $$
declare
  v_r record; v_resp record; v_body jsonb;
  v_credits int; v_cost int; v_n int; v_created int; v_settled int;
  v_board text[] := public.engine_cfg_list('board_sports');
  v_active text[] := public.engine_cfg_list('active_sports');
  v_periods text[] := array['1H'];
  v_day date := (now() at time zone 'America/New_York')::date;
begin
  for v_r in select * from public.engine_requests where not processed order by request_id loop
    select * into v_resp from net._http_response where id = v_r.request_id;
    if not found then
      if v_r.fired_at < now() - interval '10 minutes' then
        update public.engine_requests set processed = true where request_id = v_r.request_id;
        insert into public.engine_runs (kind, sport, detail)
        values ('error', v_r.sport, 'No API response received (network timeout)');
      end if;
      continue;
    end if;

    update public.engine_requests set processed = true where request_id = v_r.request_id;

    -- Each response is handled in its own sub-transaction: a payload that blows
    -- up can be logged and skipped, but can never roll back the whole engine
    -- tick (which would re-fail every minute and stop all polling behind it).
    begin
    begin
      v_credits := nullif(coalesce(v_resp.headers->>'x-requests-remaining',
                                   v_resp.headers->>'X-Requests-Remaining'), '')::numeric::int;
    exception when others then v_credits := null; end;
    if v_credits is not null then
      update public.engine_state set credits_remaining = v_credits, updated_at = now() where id = 1;
    end if;

    if v_resp.error_msg is not null or coalesce(v_resp.timed_out, false) then
      insert into public.engine_runs (kind, sport, detail)
      values ('error', v_r.sport, left(coalesce(v_resp.error_msg, 'Request timed out'), 200));
      continue;
    end if;

    if v_resp.status_code in (401, 403) then
      update public.app_config set value = 'false'::jsonb, updated_at = now() where key = 'engine_enabled';
      update public.engine_state
        set last_status = 'error', paused_reason = 'API key rejected — engine disabled', updated_at = now()
        where id = 1;
      insert into public.engine_runs (kind, sport, detail)
      values ('error', v_r.sport, 'API key rejected (HTTP ' || v_resp.status_code || ') — engine disabled');
      continue;
    end if;

    if v_resp.status_code = 429 then
      insert into public.engine_runs (kind, sport, detail)
      values ('error', v_r.sport, 'Rate limited by The Odds API — will retry next interval');
      continue;
    end if;

    if v_resp.status_code <> 200 then
      insert into public.engine_runs (kind, sport, detail)
      values ('error', v_r.sport, 'HTTP ' || coalesce(v_resp.status_code::text, '?') || ' from The Odds API');
      continue;
    end if;

    begin
      v_body := v_resp.content::jsonb;
    exception when others then
      insert into public.engine_runs (kind, sport, detail)
      values ('error', v_r.sport, 'Unparseable API response');
      continue;
    end;
    -- a per-event response is ONE object; every other endpoint returns an array
    if v_r.req_type = 'period' and jsonb_typeof(v_body) = 'object' then
      v_body := jsonb_build_array(v_body);
    end if;
    if jsonb_typeof(v_body) <> 'array' then
      insert into public.engine_runs (kind, sport, detail)
      values ('error', v_r.sport, 'Unexpected API response shape');
      continue;
    end if;

    v_n := jsonb_array_length(v_body);

    if v_r.req_type = 'scores' or v_r.req_type = 'scores_live' then
      v_settled := public.engine_apply_scores(v_body);
      begin
        perform public.board_apply_scores(v_body);
      exception when others then
        insert into public.engine_runs (kind, sport, detail)
        values ('error', v_r.sport, left('Board scores failed: ' || sqlerrm, 200));
      end;
      if v_r.req_type = 'scores' or v_settled > 0 then
        insert into public.engine_runs (kind, sport, events, edges_created, credits_remaining, detail)
        values ('settle', v_r.sport, v_n, v_settled,
                v_credits, v_settled || ' bet(s) auto-settled from final scores');
      end if;

    elsif v_r.req_type = 'period' then
      begin
        v_cost := nullif(coalesce(v_resp.headers->>'x-requests-last',
                                  v_resp.headers->>'X-Requests-Last'), '')::numeric::int;
      exception when others then v_cost := null; end;
      update public.games set period_cost = coalesce(v_cost, period_cost) where id = v_r.event_id;
      insert into public.engine_period_spend (day, credits, calls) values (v_day, coalesce(v_cost, 0), 1)
      on conflict (day) do update
        set credits = public.engine_period_spend.credits + excluded.credits,
            calls = public.engine_period_spend.calls + 1;
      begin
        perform public.board_ingest_events(v_r.sport, v_r.api_sport, v_body, v_periods);
      exception when others then
        insert into public.engine_runs (kind, sport, detail)
        values ('error', v_r.sport, left('Board ingest failed: ' || sqlerrm, 200));
      end;
      v_created := public.engine_scan_events(v_r.sport, v_body, v_r.sport = any(v_active), v_periods);
      if v_created > 0 then
        insert into public.engine_runs (kind, sport, events, edges_created, credits_remaining, detail)
        values ('scan', v_r.sport, v_n, v_created, v_credits,
                '1H lines scanned · ' || v_created || ' new edge(s)');
      end if;

    else
      insert into public.engine_sport_state (sport, last_polled_at, last_events)
      values (v_r.api_sport, now(), v_n)
      on conflict (sport) do update set last_events = excluded.last_events;

      if v_r.sport = any(v_board) then
        begin
          perform public.board_ingest_events(v_r.sport, v_r.api_sport, v_body, array['FG']);
        exception when others then
          insert into public.engine_runs (kind, sport, detail)
          values ('error', v_r.sport, left('Board ingest failed: ' || sqlerrm, 200));
        end;
      end if;

      -- verification always runs; new-edge hunting only for monitored sports
      v_created := public.engine_scan_events(v_r.sport, v_body, v_r.sport = any(v_active), array['FG']);

      insert into public.engine_runs (kind, sport, events, edges_created, credits_remaining, detail)
      values ('scan', v_r.sport, v_n, v_created, v_credits,
              v_n || ' game(s) scanned · ' || v_created || ' new edge(s)');
    end if;
    exception when others then
      insert into public.engine_runs (kind, sport, detail)
      values ('error', v_r.sport, left('Response skipped — ' || sqlerrm, 200));
    end;
  end loop;

  delete from public.engine_requests where processed and fired_at < now() - interval '1 day';
  delete from public.engine_runs where at < now() - interval '14 days';
end;
$$;

-- 1H's 4 markets cost roughly 1/6 of the old 24-market fetch, so the same
-- daily cap now buys a much faster refresh — the client is fine with 15 min.
update public.app_config set value = '15'::jsonb
  where key = 'period_refresh_minutes' and value = '120'::jsonb;

-- tidy up lines for periods that are no longer fetched (harmless if left,
-- but nothing will ever read them again since the UI no longer offers the
-- chips — see lib/odds.ts)
delete from public.game_lines where period in ('2H', '1Q', '2Q', '3Q', '4Q');
